"""Shared infrastructure for the attacks package.

Houses the abstract `BaseAttack` PSSU loop, scoring functions,
the local Ollama agent, model registry, environment configuration,
and academic benchmark loaders.
"""

from aaps.attacks._core.base_attack import AttackConfig, AttackResult, BaseAttack
from aaps.attacks._core.benchmarks import (
    VALID_BENCHMARKS,
    BenchmarkGoal,
    list_categories,
    load_all_benchmarks,
    load_benchmark,
)
from aaps.attacks._core.config import (
    LITELLM_ATTACKER_MODEL,
    LITELLM_JUDGE_MODEL,
    OLLAMA_HELPER_MODEL,
    OLLAMA_JUDGE_MODEL,
    OLLAMA_TARGET_MODEL,
    OLLAMA_URL,
    OPENROUTER_API_KEY,
    OPENROUTER_ATTACKER_MODEL,
    OPENROUTER_JUDGE_MODEL,
    OPENROUTER_VICTIM_MODEL,
    USE_LITELLM,
)
from aaps.attacks._core.local_agent import (
    AVAILABLE_TOOLS,
    DEFAULT_SYSTEM_PROMPT,
    MINIMAL_SYSTEM_PROMPT,
    LocalAgent,
    MemoryEntry,
    OllamaError,
)
from aaps.attacks._core.model_registry import (
    ALL_MODELS,
    NON_TOOL,
    TOOL_CAPABLE,
    get_available_models,
    get_model_endpoint,
    is_remote,
    is_tool_capable,
    load_models_config,
    non_tool_models,
    register_model,
    tool_capable_models,
)
from aaps.attacks._core.scoring import (
    SUCCESS_THRESHOLD,
    composite_score,
    get_litellm_judge,
    llm_judge_score,
    perplexity_score,
    secret_key_score,
    tool_call_score,
)

__all__ = [
    "AttackConfig",
    "AttackResult",
    "BaseAttack",
    "BenchmarkGoal",
    "VALID_BENCHMARKS",
    "list_categories",
    "load_all_benchmarks",
    "load_benchmark",
    "LITELLM_ATTACKER_MODEL",
    "LITELLM_JUDGE_MODEL",
    "OLLAMA_HELPER_MODEL",
    "OLLAMA_JUDGE_MODEL",
    "OLLAMA_TARGET_MODEL",
    "OLLAMA_URL",
    "OPENROUTER_API_KEY",
    "OPENROUTER_ATTACKER_MODEL",
    "OPENROUTER_JUDGE_MODEL",
    "OPENROUTER_VICTIM_MODEL",
    "USE_LITELLM",
    "AVAILABLE_TOOLS",
    "DEFAULT_SYSTEM_PROMPT",
    "MINIMAL_SYSTEM_PROMPT",
    "LocalAgent",
    "MemoryEntry",
    "OllamaError",
    "ALL_MODELS",
    "NON_TOOL",
    "TOOL_CAPABLE",
    "get_available_models",
    "get_model_endpoint",
    "is_remote",
    "is_tool_capable",
    "load_models_config",
    "non_tool_models",
    "register_model",
    "tool_capable_models",
    "SUCCESS_THRESHOLD",
    "composite_score",
    "get_litellm_judge",
    "llm_judge_score",
    "perplexity_score",
    "secret_key_score",
    "tool_call_score",
]
